# Generated by Django 5.0.6 on 2024-06-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControladorMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MotorDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VOLTAJE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CORRIENTE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxVelocidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rpm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('torque', models.DecimalField(decimal_places=2, max_digits=5)),
                ('controladorMotor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Carrito.controladormotor')),
            ],
        ),
    ]
