# Generated by Django 5.0.6 on 2024-06-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controladormotor',
            name='VOLTAJE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='controladormotor',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controladormotor',
            name='nombre',
            field=models.CharField(default='Controlador de Motor', max_length=50),
        ),
        migrations.AddField(
            model_name='motordc',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motordc',
            name='nombre',
            field=models.CharField(default='Motor DC', max_length=50),
        ),
        migrations.AlterField(
            model_name='controladormotor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
