# Generated by Django 5.0.6 on 2024-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('VOLTAJE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CORRIENTE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('rangoOperacion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('VOLTAJE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CORRIENTE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('rangoOperacion', models.CharField(max_length=50)),
                ('areaDeteccion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorProximidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('VOLTAJE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CORRIENTE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('rangoOperacion', models.CharField(max_length=50)),
                ('frecuencia', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('VOLTAJE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CORRIENTE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('rangoOperacion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
